remove data field parser
ElrondNetwork/elastic-indexer-go pull request #102
Opened 2022-01-27 08:42 UTC by miiu96

2022-01-27 08:45 UTC, bogdan-rosianu requested changes

2022-01-27 08:45 UTC, bogdan-rosianu commented on go.mod
> +	github.com/ElrondNetwork/elrond-vm-common v1.3.1-0.20220126165517-c025fc81ca7b
proper release

2022-06-15 12:55 UTC, miiu96 commented on go.mod
> +	github.com/ElrondNetwork/elrond-vm-common v1.3.1-0.20220126165517-c025fc81ca7b
done.

2022-06-15 13:43 UTC, mariusmihaic approved these changes

2022-06-15 14:15 UTC, merged