Refactor and bug fix [WIP]
ElrondNetwork/elastic-indexer-go pull request #144
Opened 2022-05-13 11:18 UTC by miiu96

2022-05-17 09:08 UTC, bogdan-rosianu requested changes

2022-05-17 09:08 UTC, bogdan-rosianu commented on integrationtests/testdata/nftTransferCrossShard/tx-complete-with-status.json
> +    "COLECTIE-26c188-01"
COLLECTION* ?

2022-05-23 07:57 UTC, miiu96 commented on integrationtests/testdata/nftTransferCrossShard/tx-complete-with-status.json
> +    "COLECTIE-26c188-01"
done.

2022-05-23 09:04 UTC, dragos-rebegea approved these changes

2022-05-23 10:50 UTC, merged