Prepare remove tx fee handler
ElrondNetwork/elastic-indexer-go pull request #164
Opened 2022-07-27 12:26 UTC by miiu96

- Integrated new `elrond-go-core`
- Removed `TransactionsFeeHandler`

2022-08-17 14:22 UTC, sstanculeanu submitted a review, later dismissed

2022-08-29 12:29 UTC, sstanculeanu approved these changes

2022-08-29 14:14 UTC, bogdan-rosianu requested changes
please run Inspect Code from your IDE. You will find some grammar issues, alongside with unsorted imports

2022-08-29 14:14 UTC, bogdan-rosianu commented on mock/dbTransactionsHandlerStub.go
> +func (tps *DBTransactionProcessorStub) SerializeTransactionsFeeData(_ map[string]*data.FeeData, _ *data.BufferSlice, _ string) error {
missing comment

2022-08-29 14:14 UTC, bogdan-rosianu commented on process/transactions/serialize.go
> +// SerializeScResults will serialize the provided smart contract results in a way that ElasticSearch expects a bulk request
Elasticsearch

2022-08-29 14:14 UTC, bogdan-rosianu commented on process/transactions/serialize.go
> +// SerializeReceipts will serialize the receipts in a way that ElasticSearch expects a bulk request
Elasticsearch

2022-08-29 14:14 UTC, bogdan-rosianu commented on factory/indexerFactory.go
> -		return indexer.ErrNilTransactionFeeCalculator
remove this err from errors.go

2022-08-29 14:14 UTC, bogdan-rosianu commented on process/elasticProcessor.go
> +	"github.com/ElrondNetwork/elrond-go-core/data/outport"
imports not sorted

2022-08-29 14:36 UTC, miiu96 commented on mock/dbTransactionsHandlerStub.go
> +func (tps *DBTransactionProcessorStub) SerializeTransactionsFeeData(_ map[string]*data.FeeData, _ *data.BufferSlice, _ string) error {
added

2022-08-29 14:36 UTC, miiu96 commented on process/transactions/serialize.go
> +// SerializeScResults will serialize the provided smart contract results in a way that ElasticSearch expects a bulk request
done

2022-08-29 14:36 UTC, miiu96 commented on process/transactions/serialize.go
> +// SerializeReceipts will serialize the receipts in a way that ElasticSearch expects a bulk request
done

2022-08-29 14:36 UTC, miiu96 commented on factory/indexerFactory.go
> -		return indexer.ErrNilTransactionFeeCalculator
done.

2022-08-29 14:37 UTC, miiu96 commented on process/elasticProcessor.go
> +	"github.com/ElrondNetwork/elrond-go-core/data/outport"
done.

2022-08-29 14:41 UTC, bogdan-rosianu approved these changes

2022-08-29 14:42 UTC, sstanculeanu approved these changes

2022-08-29 14:42 UTC, merged