Delegators list
ElrondNetwork/elastic-indexer-go pull request #66
Opened 2021-10-12 07:49 UTC by miiu96

- Added a new Elasticsearch index `delegators` that will keep a list will all the users that have delegated funds on the delegation contracts.

2021-10-13 08:34 UTC, bogdan-rosianu requested changes

2021-10-13 08:34 UTC, bogdan-rosianu commented on converters/balanceToFloat.go
> +func (bc *balanceConverter) IsInterfaceNil() bool {
add comment

2021-10-13 08:34 UTC, bogdan-rosianu commented on data/delegators.go
> +type Delegator struct {
comment

2021-10-13 08:34 UTC, bogdan-rosianu commented on process/logsevents/logsAndEventsProcessor.go
> +		issueESDTProc := newESDTIssueProcessor()
esdtIssueProc

2021-10-13 08:34 UTC, bogdan-rosianu commented on process/logsevents/serialize.go
> +	return base64.StdEncoding.EncodeToString(hashBytes)
I don't think this is ok. if we want to search in this index based on an address and a contract, we'd have to convert it to base64 at first. maybe stick to plain string

2021-10-13 08:34 UTC, bogdan-rosianu commented on process/logsevents/serialize.go
> +func (lep *logsAndEventsProcessor) SerializeDelegators(delegators map[string]*data.Delegator) ([]*bytes.Buffer, error) {
comment

2021-10-14 11:22 UTC, miiu96 commented on process/logsevents/logsAndEventsProcessor.go
> +		issueESDTProc := newESDTIssueProcessor()
renamed.

2021-10-14 11:27 UTC, miiu96 commented on process/logsevents/serialize.go
> +func (lep *logsAndEventsProcessor) SerializeDelegators(delegators map[string]*data.Delegator) ([]*bytes.Buffer, error) {
added

2021-10-14 11:27 UTC, miiu96 commented on converters/balanceToFloat.go
> +	if balance == nil || balance == big.NewInt(0) {
added.

2021-10-14 11:28 UTC, miiu96 commented on converters/balanceToFloat.go
> +		dividerForDenomination: math.Pow(10, float64(core.MaxInt(denomination, 0))),
you right. no longer needed.

2021-10-14 11:28 UTC, miiu96 commented on data/delegators.go
> +type Delegator struct {
added

2021-10-14 11:32 UTC, miiu96 commented on process/logsevents/delegatorsProcessor.go
> +	// topics[0] = delegated value / unDelegated value / withdraw value/ reDelegated value
fixed on the `elrond-go` side in case of redelegate

2021-10-14 11:33 UTC, miiu96 commented on process/logsevents/logsAndEventsProcessor.go
> +	hahser           hashing.Hasher
renamed.

2021-10-14 11:36 UTC, miiu96 commented on converters/interface.go
> +type BalanceConverter interface {
moved.

2021-10-14 13:43 UTC, bogdan-rosianu requested changes

2021-10-14 13:43 UTC, bogdan-rosianu commented on converters/balanceToFloat.go
> +	if balance == nil || balance == zero {
this big int comparison won't work. please compare the bytes of the big int values

2021-10-14 13:43 UTC, bogdan-rosianu commented on integrationtests/issueToken_test.go
> +	require.JSONEq(t, expectedTokenSemiAfterTransferOwnership, string(genericResponse.Docs[0].Source))
:+1:

2021-10-14 13:43 UTC, bogdan-rosianu commented on process/logsevents/serialize.go
> +		`"source": "if (!ctx._source.containsKey('ownersHistory')) { ctx._source.ownersHistory = [ params.elem ]; ctx._source.currentOwner = params.owner; } else {  ctx._source.currentOwner = params.owner;
`ctx._source.currentOwner = params.owner;` exists on both cases. move it outside the if

2021-10-16 07:42 UTC, miiu96 commented on process/logsevents/delegatorsProcessor.go
> +	b, _ := strconv.ParseBool(string(boolBytes))
added.

2021-10-16 07:43 UTC, miiu96 commented on process/logsevents/serialize.go
> +	ownerDataSerialized, err := json.Marshal(&currentOwnerData)
fixed.

2021-10-16 08:13 UTC, bogdan-rosianu approved these changes

2021-10-16 09:30 UTC, iulianpascalau approved these changes

2021-10-16 17:34 UTC, merged