index modifier tool initial impl
ElrondNetwork/elastic-indexer-go pull request #85
Opened 2021-12-15 10:22 UTC by miiu96

2021-12-21 08:42 UTC, dragos-rebegea submitted a review, later dismissed

2021-12-21 09:07 UTC, bogdan-rosianu requested changes

2021-12-21 09:07 UTC, bogdan-rosianu commented on tools/index-modifier/pkg/alterindex/reindex.go
> +func CreateIndexModifier(scrollClientAddress, bulkClientAddress string) (*indexModifier, error) {
add comment

2021-12-21 09:07 UTC, bogdan-rosianu commented on tools/index-modifier/pkg/alterindex/reindex.go
> +	client2 "github.com/ElrondNetwork/elastic-indexer-go/client"
rename `client2` to `indexerClient`

2021-12-21 09:07 UTC, bogdan-rosianu commented on tools/index-modifier/pkg/alterindex/reindex.go
> +func (im *indexModifier) AlterIndex(indexRead, indexWrite string, modifier func(responseBytes []byte) ([]*bytes.Buffer, error)) error {
comment

2021-12-21 09:07 UTC, bogdan-rosianu commented on tools/index-modifier/pkg/client/client.go
> +		return nil, fmt.Errorf("error response: %s", res)
shouldn't the body be closed even if there is an error?

2021-12-21 09:07 UTC, bogdan-rosianu commented on tools/index-modifier/pkg/modifiers/scrsModifier.go
> +func NewSCRsModifier() (*scrsModifier, error) {
comment

2021-12-21 09:07 UTC, bogdan-rosianu commented on tools/index-modifier/pkg/modifiers/scrsModifier.go
> +func (sm *scrsModifier) Modify(responseBody []byte) ([]*bytes.Buffer, error) {
comment

2021-12-21 09:07 UTC, bogdan-rosianu commented on tools/index-modifier/pkg/modifiers/txsModifier.go
> +func NewTxsModifier() (*txsModifier, error) {
comment

2021-12-21 09:07 UTC, bogdan-rosianu commented on tools/index-modifier/pkg/modifiers/txsModifier.go
> +func (tm *txsModifier) Modify(responseBody []byte) ([]*bytes.Buffer, error) {
comment

2021-12-21 10:50 UTC, miiu96 commented on tools/index-modifier/go.mod
> +	github.com/ElrondNetwork/elrond-vm-common v1.2.7 // indirect
done.

2021-12-21 10:53 UTC, miiu96 commented on tools/index-modifier/pkg/alterindex/interface.go
> +type ScrollClient interface {
added.

2021-12-21 10:54 UTC, miiu96 commented on tools/index-modifier/pkg/alterindex/reindex.go
> +func CreateIndexModifier(scrollClientAddress, bulkClientAddress string) (*indexModifier, error) {
added

2021-12-21 10:54 UTC, miiu96 commented on tools/index-modifier/pkg/alterindex/reindex.go
> +	client2 "github.com/ElrondNetwork/elastic-indexer-go/client"
done.

2021-12-21 10:55 UTC, miiu96 commented on tools/index-modifier/pkg/alterindex/reindex.go
> +func (im *indexModifier) AlterIndex(indexRead, indexWrite string, modifier func(responseBytes []byte) ([]*bytes.Buffer, error)) error {
added

2021-12-21 10:59 UTC, miiu96 commented on tools/index-modifier/pkg/modifiers/scrsModifier.go
> +func NewSCRsModifier() (*scrsModifier, error) {
done.

2021-12-21 10:59 UTC, miiu96 commented on tools/index-modifier/pkg/modifiers/scrsModifier.go
> +func (sm *scrsModifier) Modify(responseBody []byte) ([]*bytes.Buffer, error) {
added

2021-12-21 11:00 UTC, miiu96 commented on tools/index-modifier/pkg/modifiers/txsModifier.go
> +func NewTxsModifier() (*txsModifier, error) {
added

2021-12-21 11:00 UTC, miiu96 commented on tools/index-modifier/pkg/modifiers/txsModifier.go
> +func (tm *txsModifier) Modify(responseBody []byte) ([]*bytes.Buffer, error) {
added

2021-12-21 14:46 UTC, bogdan-rosianu approved these changes

2021-12-28 12:40 UTC, dragos-rebegea approved these changes

2021-12-28 12:49 UTC, merged